I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scenario.rpy", line 9231, in script
    mt "Я вас категорически приветствую."
Exception: Sayer 'mt' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scenario.rpy", line 9231, in script
    mt "Я вас категорически приветствую."
  File "renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'mt' is not defined.

Windows-7-6.1.7601-SP1
Ren'Py 7.4.11.2266
Skitetsky REMASTER 1.0
Sat Feb 25 16:49:32 2023
